name: Deploy Client React

on:
  push:
    paths:
      - "apps/client-react/**"
      - "packages/ui/**"
      - "packages/common/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu@ec2-13-232-166-95.ap-south-1.compute.amazonaws.com "sudo bash /home/ubuntu/deploy-test/apps/client-react/deploy.sh"
